// Command pin-images resolves every container image in core/distro's
// release table to its current registry digest and prints the Go table rows
// to paste into core/distro/distro.go's ImageDigest fields.
//
// core/distro/distro.go is frozen (docs/dev/contract-brief.md) and may be
// read by other packages while this runs, so this tool never edits it: it only
// prints. A maintainer copies the printed rows in by hand.
//
// Usage:
//
//	go run ./hack/pin-images.go                    # docker, every release, stdout
//	go run ./hack/pin-images.go -runtime podman
//	go run ./hack/pin-images.go -codename bookworm  # just one release
//	go run ./hack/pin-images.go -out digests.txt
//
// This shells out to `docker buildx imagetools inspect <image>` (bundled
// with any current Docker CLI) rather than a daemon SDK, matching the rest
// of the container backend (exec the docker/podman CLI, no
// daemon SDK dependency). `imagetools inspect` prints the manifest LIST's
// own content digest -- the same thing `image@sha256:...` in
// core/distro.Release.Ref() pins -- without requiring a local pull of every
// architecture's layers. Podman has no direct equivalent subcommand; run
// with `-runtime docker` (the default) for now, or adapt -inspect-args.
package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/inferops/debark/core/distro"
)

func main() {
	runtimeFlag := flag.String("runtime", "docker", "container CLI to use (docker or podman)")
	inspectArgs := flag.String("inspect-args", "buildx imagetools inspect", "subcommand+args run as: <runtime> <inspect-args> <image>")
	codename := flag.String("codename", "", "only resolve the release with this codename (default: every release in the table)")
	outPath := flag.String("out", "", "write the rows to this file instead of stdout")
	timeout := flag.Duration("timeout", 60*time.Second, "per-image timeout")
	flag.Parse()

	releases := distro.All()
	if *codename != "" {
		r, ok := distro.ByCodename(*codename)
		if !ok {
			fmt.Fprintf(os.Stderr, "pin-images: unknown codename %q\n", *codename)
			os.Exit(1)
		}
		releases = []distro.Release{r}
	}

	runtimePath, err := exec.LookPath(*runtimeFlag)
	if err != nil {
		fmt.Fprintf(os.Stderr, "pin-images: %s not found on PATH: %v\n", *runtimeFlag, err)
		os.Exit(2)
	}

	var (
		rows   []string
		failed []string
	)
	for _, r := range releases {
		if r.Image == "" {
			continue
		}
		fmt.Fprintf(os.Stderr, "resolving %-8s %-6s (%-9s) %s ... ", r.DistroID, r.VersionID, r.Codename, r.Image)
		ctx, cancel := context.WithTimeout(context.Background(), *timeout)
		digest, err := resolveDigest(ctx, runtimePath, strings.Fields(*inspectArgs), r.Image)
		cancel()
		if err != nil {
			fmt.Fprintf(os.Stderr, "FAILED: %v\n", err)
			failed = append(failed, fmt.Sprintf("%s %s (%s): %v", r.DistroID, r.VersionID, r.Codename, err))
			continue
		}
		fmt.Fprintln(os.Stderr, digest)
		r.ImageDigest = digest
		rows = append(rows, renderRow(r))
	}

	out := io.Writer(os.Stdout)
	if *outPath != "" {
		f, err := os.Create(*outPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "pin-images: %v\n", err)
			os.Exit(2)
		}
		defer f.Close()
		out = f
	}
	fmt.Fprintln(out, "// Paste these rows into core/distro/distro.go's releases table (match by")
	fmt.Fprintln(out, "// DistroID+VersionID), replacing the corresponding row. Generated by")
	fmt.Fprintf(out, "// hack/pin-images.go, %s.\n", time.Now().UTC().Format("2006-01-02"))
	for _, row := range rows {
		fmt.Fprintln(out, row)
	}

	if len(failed) > 0 {
		sort.Strings(failed)
		fmt.Fprintf(os.Stderr, "\n%d image(s) could not be resolved:\n", len(failed))
		for _, f := range failed {
			fmt.Fprintf(os.Stderr, "  - %s\n", f)
		}
		os.Exit(1)
	}
}

// digestLineRe matches `docker buildx imagetools inspect`'s "Digest:" line,
// e.g. "Digest:    sha256:1e1c...".
var digestLineRe = regexp.MustCompile(`(?m)^Digest:\s*(sha256:[0-9a-f]{64})\s*$`)

// resolveDigest runs <runtimePath> <inspectArgs...> <image> and extracts the
// manifest digest from its output.
func resolveDigest(ctx context.Context, runtimePath string, inspectArgs []string, image string) (string, error) {
	args := append(append([]string(nil), inspectArgs...), image)
	cmd := exec.CommandContext(ctx, runtimePath, args...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("%s %s: %w\n%s", runtimePath, strings.Join(args, " "), err, indent(out))
	}
	m := digestLineRe.FindSubmatch(out)
	if m == nil {
		return "", fmt.Errorf("no \"Digest:\" line in output:\n%s", indent(out))
	}
	return string(m[1]), nil
}

func indent(b []byte) string {
	lines := strings.Split(strings.TrimRight(string(b), "\n"), "\n")
	for i, l := range lines {
		lines[i] = "    " + l
	}
	return strings.Join(lines, "\n")
}

// renderRow renders one core/distro.Release as a Go struct literal in
// exactly the style core/distro/distro.go's releases table already uses
// (field order: DistroID, VersionID, Codename, Supported (only if true),
// Image, ImageDigest, EOL (only if set)), so it can be pasted in verbatim.
func renderRow(r distro.Release) string {
	var b strings.Builder
	fmt.Fprintf(&b, "{DistroID: %s, VersionID: %q, Codename: %q", distroIDIdent(r.DistroID), r.VersionID, r.Codename)
	if r.Supported {
		b.WriteString(", Supported: true")
	}
	fmt.Fprintf(&b, ", Image: %q", r.Image)
	if r.ImageDigest != "" {
		fmt.Fprintf(&b, ", ImageDigest: %q", r.ImageDigest)
	}
	if r.EOL != "" {
		fmt.Fprintf(&b, ", EOL: %q", r.EOL)
	}
	b.WriteString("},")
	return b.String()
}

// distroIDIdent renders a distro id as the Go identifier distro.go's table
// uses (the Debian/Ubuntu constants), falling back to a quoted string for
// anything else so output is always valid Go.
func distroIDIdent(id string) string {
	switch id {
	case distro.Debian:
		return "Debian"
	case distro.Ubuntu:
		return "Ubuntu"
	default:
		return fmt.Sprintf("%q", id)
	}
}
