package install

import (
	"encoding/json"
	"reflect"
	"strings"
	"testing"

	"github.com/inferops/debark/core/snapshot"
)

// This file is the tripwire under bundleSnapshotDoc, and it is the ONLY place
// in core/install that names core/snapshot.
//
// core/install deliberately does not import core/snapshot — see the long note
// on resolveBundleDir in bundle.go, and the one on bundleSnapshotDoc in
// basedivergence.go. This package is the only part of debark that runs on
// the air-gapped machine; it stays small enough to audit and to package in a
// distribution, and it does not acquire the capture/validation/archive
// surface of core/snapshot in order to read three fields out of a JSON
// document. bundleSnapshotDoc is therefore a hand-copied subset of
// debark.snapshot/v1, and hand-copied subsets drift: a tag renamed in
// core/snapshot would leave this package silently decoding zero values, which
// for origin.kind means "not synthesized" and so means the divergence report
// vanishing without anything failing.
//
// The import below is TEST-ONLY, which is precisely why it is allowed to
// exist. A _test.go import is not part of the shipped binary's dependency
// graph — `go build ./cmd/...` never compiles core/snapshot on its account —
// so it buys the guard without spending the boundary the guard protects.
// Do not "tidy" it away, and do not conclude from it that the production code
// may import core/snapshot too. If you need to know whether that is still
// true, `go list -deps ./core/install` is the question; this file will not
// appear in the answer.

// TestBundleSnapshotDocDecodesARealSnapshot marshals a real
// snapshot.Snapshot — the actual frozen type, from the actual package — and
// asserts the local subset reads back exactly what was written. Generating
// the fixture from the type it is checking against is the point here: the
// thing under test is agreement between two declarations, so the other
// declaration has to be the oracle. (Contrast the trap this project records:
// a fixture generated by the same RULE the implementation applies has no
// oracle. Here the rule is encoding/json's, shared by both sides, and the two
// struct declarations are the independent halves.)
func TestBundleSnapshotDocDecodesARealSnapshot(t *testing.T) {
	real := snapshot.Snapshot{
		SchemaVersion: snapshot.SchemaVersion,
		CreatedAt:     "2026-09-06T12:00:00Z",
		Tool:          snapshot.Tool{Name: "debark", Version: "1.0.0"},
		Target: snapshot.Target{
			DistroID: "ubuntu", VersionID: "26.04", Codename: "resolute", Arch: "amd64",
			APTVersion: "3.0.0", DpkgVersion: "1.22.6",
		},
		Origin: snapshot.Origin{
			Kind:             snapshot.OriginSynthesized,
			BaseID:           "ubuntu:26.04/desktop",
			Source:           snapshot.OriginSourceBuiltin,
			SourceDigest:     strings.Repeat("ab", 32),
			AssumedInstalled: []string{"bash:amd64", "libc6:amd64", "zlib1g:i386"},
		},
	}

	raw, err := json.Marshal(&real)
	if err != nil {
		t.Fatalf("marshal snapshot.Snapshot: %v", err)
	}

	var local bundleSnapshotDoc
	if err := json.Unmarshal(raw, &local); err != nil {
		t.Fatalf("bundleSnapshotDoc cannot decode a real snapshot.Snapshot: %v", err)
	}

	if local.Origin.Kind != real.Origin.Kind {
		t.Errorf("origin.kind decoded as %q, want %q - a json tag has drifted from core/snapshot/types.go",
			local.Origin.Kind, real.Origin.Kind)
	}
	if local.Origin.BaseID != real.Origin.BaseID {
		t.Errorf("origin.base_id decoded as %q, want %q", local.Origin.BaseID, real.Origin.BaseID)
	}
	if !reflect.DeepEqual(local.Origin.AssumedInstalled, real.Origin.AssumedInstalled) {
		t.Errorf("origin.assumed_installed decoded as %v, want %v",
			local.Origin.AssumedInstalled, real.Origin.AssumedInstalled)
	}
}

// TestBundleSnapshotDocDecodesACapturedSnapshot is the other half, and it is
// the half that matters most. The dangerous drift is not a synthesized
// snapshot that fails to decode - that is loud, because the report goes
// missing on a bundle that should have one. It is a captured snapshot whose
// kind field this package reads as something other than "captured", because
// the check would then run against an empty assumed set and report every
// bundle as resting on an assumption it does not rest on.
func TestBundleSnapshotDocDecodesACapturedSnapshot(t *testing.T) {
	real := snapshot.Snapshot{
		SchemaVersion: snapshot.SchemaVersion,
		Origin:        snapshot.Origin{Kind: snapshot.OriginCaptured},
	}
	raw, err := json.Marshal(&real)
	if err != nil {
		t.Fatalf("marshal snapshot.Snapshot: %v", err)
	}
	var local bundleSnapshotDoc
	if err := json.Unmarshal(raw, &local); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if local.Origin.Kind != snapshot.OriginCaptured {
		t.Fatalf("origin.kind decoded as %q, want %q", local.Origin.Kind, snapshot.OriginCaptured)
	}
	if local.Origin.Kind == originSynthesized {
		t.Fatal("a captured snapshot decoded as synthesized")
	}
	if len(local.Origin.AssumedInstalled) != 0 {
		t.Errorf("a captured snapshot decoded with %d assumed packages; core/snapshot's Validate refuses that field on a captured snapshot",
			len(local.Origin.AssumedInstalled))
	}
}

// TestLocalSnapshotConstantsMatchCoreSnapshot pins the two string constants
// this package copied rather than imported. They are not covered by the
// round-trips above: a wrong value for either would compile, decode
// perfectly, and simply never match.
func TestLocalSnapshotConstantsMatchCoreSnapshot(t *testing.T) {
	if originSynthesized != snapshot.OriginSynthesized {
		t.Errorf("originSynthesized = %q, but snapshot.OriginSynthesized = %q",
			originSynthesized, snapshot.OriginSynthesized)
	}
	if snapshotDocName != snapshot.DocumentName {
		t.Errorf("snapshotDocName = %q, but snapshot.DocumentName = %q",
			snapshotDocName, snapshot.DocumentName)
	}
}

// TestSynthesizedSnapshotFixtureIsAValidSnapshot proves the fixture the
// behaviour tests install into their bundles is a document core/snapshot
// itself would accept, not a shape only this package's reduced decoder
// tolerates. Without it, every test in basedivergence_test.go could be
// passing against a snapshot.json debark never writes - the same vacuous
// shape as a fake that cannot express the failure being asserted.
func TestSynthesizedSnapshotFixtureIsAValidSnapshot(t *testing.T) {
	for _, tc := range []struct {
		name string
		doc  string
	}{
		{"synthesized", synthesizedSnapshotJSON("ubuntu:26.04/desktop", []string{"bash:amd64", "zlib1g:i386"})},
		{"captured", capturedSnapshotJSON()},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var s snapshot.Snapshot
			if err := json.Unmarshal([]byte(tc.doc), &s); err != nil {
				t.Fatalf("fixture does not parse as a snapshot.Snapshot: %v", err)
			}
			if err := snapshot.Validate(&s); err != nil {
				t.Fatalf("fixture is not a valid debark.snapshot/v1 document: %v", err)
			}
		})
	}
}
