// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddLocalDebs(arg1:Array<string>):Promise<app.SelectionSummary>;

export function AddPackageList(arg1:string):Promise<app.SelectionSummary>;

export function AddPackages(arg1:Array<string>):Promise<app.SelectionSummary>;

export function AddURLs(arg1:Array<app.URLInput>):Promise<app.SelectionSummary>;

export function AppInfo():Promise<app.AppInfo>;

export function Bind():Promise<Array<any>>;

export function BuildLog(arg1:number,arg2:number):Promise<app.BuildLogPage>;

export function BuildStatus():Promise<app.BuildStatus>;

export function CancelBuild():Promise<app.Result>;

export function CancelCatalogBuild():Promise<app.Result>;

export function CancelExport():Promise<app.Result>;

export function CancelReadinessCheck():Promise<app.Result>;

export function CancelVerify():Promise<app.Result>;

export function CatalogStatus():Promise<app.CatalogStatus>;

export function Categories():Promise<app.CategoriesResult>;

export function ChooseDirectory(arg1:string,arg2:string):Promise<app.FilePickResult>;

export function ChooseLocalDebs():Promise<app.FilePickResult>;

export function ChooseSigningKey():Promise<app.FilePickResult>;

export function ChooseSnapshotFile():Promise<app.FilePickResult>;

export function ClearSelection():Promise<app.SelectionSummary>;

export function ClearTarget():Promise<app.Result>;

export function CopyToClipboard(arg1:string):Promise<app.Result>;

export function CurrentTarget():Promise<app.TargetResult>;

export function ExportStatus():Promise<app.ExportStatus>;

export function GetPackage(arg1:string):Promise<app.PackageResult>;

export function InspectDestination(arg1:app.ExportOptions):Promise<app.DestinationView>;

export function InspectSnapshot(arg1:string):Promise<app.SnapshotResult>;

export function LifecycleStatus():Promise<app.LifecycleView>;

export function ListBases(arg1:string):Promise<app.BasesResult>;

export function ListVolumes():Promise<app.VolumesResult>;

export function PackageRows(arg1:Array<string>):Promise<app.PackageRowsResult>;

export function ParsePackageList(arg1:string):Promise<app.ParsedList>;

export function PlanExport(arg1:app.ExportOptions):Promise<app.ExportPlanResult>;

export function PreviewCommand(arg1:app.BuildOptions):Promise<app.CommandPreview>;

export function Readiness():Promise<app.ReadinessReport>;

export function RecheckReadiness(arg1:string):Promise<app.Result>;

export function RemovePackages(arg1:Array<string>):Promise<app.SelectionSummary>;

export function RequestClose():Promise<app.Result>;

export function RevealPath(arg1:string):Promise<app.Result>;

export function RunReadinessAction(arg1:string):Promise<app.Result>;

export function SearchPackages(arg1:app.SearchQuery):Promise<app.SearchResult>;

export function SelectTarget(arg1:app.TargetSelection):Promise<app.TargetResult>;

export function Selection():Promise<app.SelectionSummary>;

export function SelectionKeys():Promise<app.SelectionKeysResult>;

export function SelectionPage(arg1:number,arg2:number):Promise<app.SelectionPage>;

export function StartBuild(arg1:app.BuildOptions):Promise<app.Result>;

export function StartCatalogBuild(arg1:boolean):Promise<app.Result>;

export function StartExport(arg1:app.ExportOptions):Promise<app.Result>;

export function StartReadinessCheck():Promise<app.Result>;

export function StartVerify(arg1:string):Promise<app.Result>;

export function SupportedArchitectures():Promise<app.ArchesResult>;

export function UndoSelection(arg1:string):Promise<app.SelectionSummary>;

export function VerifyStatus():Promise<app.VerifyStatus>;
