// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLocalDebs(arg1) {
  return window['go']['app']['App']['AddLocalDebs'](arg1);
}

export function AddPackageList(arg1) {
  return window['go']['app']['App']['AddPackageList'](arg1);
}

export function AddPackages(arg1) {
  return window['go']['app']['App']['AddPackages'](arg1);
}

export function AddURLs(arg1) {
  return window['go']['app']['App']['AddURLs'](arg1);
}

export function AppInfo() {
  return window['go']['app']['App']['AppInfo']();
}

export function Bind() {
  return window['go']['app']['App']['Bind']();
}

export function BuildLog(arg1, arg2) {
  return window['go']['app']['App']['BuildLog'](arg1, arg2);
}

export function BuildStatus() {
  return window['go']['app']['App']['BuildStatus']();
}

export function CancelBuild() {
  return window['go']['app']['App']['CancelBuild']();
}

export function CancelCatalogBuild() {
  return window['go']['app']['App']['CancelCatalogBuild']();
}

export function CancelExport() {
  return window['go']['app']['App']['CancelExport']();
}

export function CancelReadinessCheck() {
  return window['go']['app']['App']['CancelReadinessCheck']();
}

export function CancelVerify() {
  return window['go']['app']['App']['CancelVerify']();
}

export function CatalogStatus() {
  return window['go']['app']['App']['CatalogStatus']();
}

export function Categories() {
  return window['go']['app']['App']['Categories']();
}

export function ChooseDirectory(arg1, arg2) {
  return window['go']['app']['App']['ChooseDirectory'](arg1, arg2);
}

export function ChooseLocalDebs() {
  return window['go']['app']['App']['ChooseLocalDebs']();
}

export function ChooseSigningKey() {
  return window['go']['app']['App']['ChooseSigningKey']();
}

export function ChooseSnapshotFile() {
  return window['go']['app']['App']['ChooseSnapshotFile']();
}

export function ClearSelection() {
  return window['go']['app']['App']['ClearSelection']();
}

export function ClearTarget() {
  return window['go']['app']['App']['ClearTarget']();
}

export function CopyToClipboard(arg1) {
  return window['go']['app']['App']['CopyToClipboard'](arg1);
}

export function CurrentTarget() {
  return window['go']['app']['App']['CurrentTarget']();
}

export function ExportStatus() {
  return window['go']['app']['App']['ExportStatus']();
}

export function GetPackage(arg1) {
  return window['go']['app']['App']['GetPackage'](arg1);
}

export function InspectDestination(arg1) {
  return window['go']['app']['App']['InspectDestination'](arg1);
}

export function InspectSnapshot(arg1) {
  return window['go']['app']['App']['InspectSnapshot'](arg1);
}

export function LifecycleStatus() {
  return window['go']['app']['App']['LifecycleStatus']();
}

export function ListBases(arg1) {
  return window['go']['app']['App']['ListBases'](arg1);
}

export function ListVolumes() {
  return window['go']['app']['App']['ListVolumes']();
}

export function PackageRows(arg1) {
  return window['go']['app']['App']['PackageRows'](arg1);
}

export function ParsePackageList(arg1) {
  return window['go']['app']['App']['ParsePackageList'](arg1);
}

export function PlanExport(arg1) {
  return window['go']['app']['App']['PlanExport'](arg1);
}

export function PreviewCommand(arg1) {
  return window['go']['app']['App']['PreviewCommand'](arg1);
}

export function Readiness() {
  return window['go']['app']['App']['Readiness']();
}

export function RecheckReadiness(arg1) {
  return window['go']['app']['App']['RecheckReadiness'](arg1);
}

export function RemovePackages(arg1) {
  return window['go']['app']['App']['RemovePackages'](arg1);
}

export function RequestClose() {
  return window['go']['app']['App']['RequestClose']();
}

export function RevealPath(arg1) {
  return window['go']['app']['App']['RevealPath'](arg1);
}

export function RunReadinessAction(arg1) {
  return window['go']['app']['App']['RunReadinessAction'](arg1);
}

export function SearchPackages(arg1) {
  return window['go']['app']['App']['SearchPackages'](arg1);
}

export function SelectTarget(arg1) {
  return window['go']['app']['App']['SelectTarget'](arg1);
}

export function Selection() {
  return window['go']['app']['App']['Selection']();
}

export function SelectionKeys() {
  return window['go']['app']['App']['SelectionKeys']();
}

export function SelectionPage(arg1, arg2) {
  return window['go']['app']['App']['SelectionPage'](arg1, arg2);
}

export function StartBuild(arg1) {
  return window['go']['app']['App']['StartBuild'](arg1);
}

export function StartCatalogBuild(arg1) {
  return window['go']['app']['App']['StartCatalogBuild'](arg1);
}

export function StartExport(arg1) {
  return window['go']['app']['App']['StartExport'](arg1);
}

export function StartReadinessCheck() {
  return window['go']['app']['App']['StartReadinessCheck']();
}

export function StartVerify(arg1) {
  return window['go']['app']['App']['StartVerify'](arg1);
}

export function SupportedArchitectures() {
  return window['go']['app']['App']['SupportedArchitectures']();
}

export function UndoSelection(arg1) {
  return window['go']['app']['App']['UndoSelection'](arg1);
}

export function VerifyStatus() {
  return window['go']['app']['App']['VerifyStatus']();
}
